### ISSUE TITLE
Error while upgrading 8.7 to 9

### ISSUE THREAD

**Issue by kiranrs** [AlmaLinux/almalinux-deploy#166]
While upgrading Almalinux 8.7 to 9 , I'm getting the following error. I followed [this ](https://www.layerstack.com/resources/tutorials/How-to-upgrade-from-AlmaLinux8-to-AlmaLinux9)article. https://www.layerstack.com/resources/tutorials/How-to-upgrade-from-AlmaLinux8-to-AlmaLinux9
![image](https://github.com/AlmaLinux/almalinux-deploy/assets/13621798/43ef554c-3fca-4258-9d1b-8970721e7952)

**Comment by andrewlukoshko** [comment]
Your system has a lot of 3rd party packages which is not supported.
Most of them are from LightSpeed repo as I see. Try to add LightSpeed repo for EL9 to:
```
/etc/leapp/files/leapp_upgrade_repositories.repo
```
This could help.

**Comment by infoensv** [comment]
hello ,
I have the same problem is there any solution

**Comment by xiekunwhy** [comment]
Hi,

Here is my problem
leapp preupgrade
==> Processing phase `configuration_phase`
====> * ipu_workflow_config
        IPU workflow config actor
==> Processing phase `FactsCollection`
====> * system_facts
        Provides data about many facts from system.
Process Process-217:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/actor.py", line 57, in process
    self.produce(systemfacts.get_repositories_status())
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/systemfacts/libraries/systemfacts.py", line 194, in get_repositories_status
    return RepositoriesFacts(repositories=repofileutils.get_parsed_repofiles())
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/repofileutils.py", line 101, in get_parsed_repofiles
    cmd = ['find', '-L'] + get_repodirs() + ['-maxdepth', '1', '-type', 'f', '-name', '*.repo']
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/repofileutils.py", line 81, in get_repodirs
    with dnf.base.Base() as base:
NameError: global name 'dnf' is not defined


=============================================================================================
Actor system_facts unexpectedly terminated with exit code: 1 - Please check the above details
=============================================================================================

Debug output written to /var/log/leapp/leapp-preupgrade.log

============================================================
                           REPORT                           
============================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

============================================================
                       END OF REPORT                        
============================================================

Answerfile has been generated at /var/log/leapp/answerfile

any suggestions?

**Comment by GMujtabaa** [comment]
This needs to follow steps post upgrade RHEL 7 to 8 then you will need to check command leapp preupgrade.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index#performing-post-upgrade-tasks-rhel-7-to-rhel-8_upgrading-from-rhel-7-to-rhel-8

**Comment by jaquice** [comment]
Hi all.  I have been trying to solve this for 4 days now with no luck.  Has anyone had this error before during a leapp upgrade from 8 to 9.

Answerfile has been generated at /var/log/leapp/answerfile
[root@otv-linuxapp01 leapp]# cat /var/log/leapp/leapp-report.txt
Risk Factor: high (error)
Title: Actor read_openssh_config unexpectedly terminated with exit code: 1
Summary: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/leapp/repository/actor_definition.py", line 74, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/actors/__init__.py", line 289, in run
    self.process(*args)
  File "/etc/leapp/repos.d/system_upgrade/common/actors/opensshconfigscanner/actor.py", line 28, in process
    readopensshconfig.scan_sshd(self.produce)
  File "/etc/leapp/repos.d/system_upgrade/common/actors/opensshconfigscanner/libraries/readopensshconfig.py", line 102, in scan_sshd
    config = parse_config(output)
  File "/etc/leapp/repos.d/system_upgrade/common/actors/opensshconfigscanner/libraries/readopensshconfig.py", line 42, in parse_config
    v = OpenSshPermitRootLogin(value=value, in_match=in_match)
  File "/usr/lib/python3.6/site-packages/leapp/models/__init__.py", line 90, in __init__
    getattr(defined_fields[field], init_method)(kwargs, field, self)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 111, in from_initialization
    self._validate_model_value(value=source_value, name=name)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 332, in _validate_model_value
    self._validate_choices(value, name)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 342, in _validate_choices
    'The value of "{name}" field must be one of "{values}"'.format(name=name, values=values))
leapp.models.fields.ModelViolationError: The value of "value" field must be one of "yes, prohibit-password, forced-commands-only, no"

Key: cbbb94dfc66307035ea5d5bad66eb1428eb6bba3

**Comment by yuravk** [comment]
Please open your `/etc/ssh/sshd_config` and check the `PermitRootLogin` option in it.
Also, the` sshd -T` might be useful to check the validity of the configuration file.
